<?php
/**
 * Staging seed, step 1: the accounts a review needs. Invented people only.
 *
 *  - client_operator: Shop manager, the account the client drives in the store operations walkthrough (PRE-07).
 *  - demo_customer:   a customer with an order history.
 *
 * Passwords are generated by staging.py and passed in the environment, so none is written in this repository.
 *
 * @package MizzeySite\Tests\Staging
 */

defined( 'ABSPATH' ) || exit;
defined( 'MIZZEY_STAGING' ) && MIZZEY_STAGING || WP_CLI::error( 'staging only' );

$passwords = json_decode( (string) getenv( 'MIZZEY_SEED_PASSWORDS' ), true );
$accounts  = array(
	'client_operator' => array( 'shop_manager', 'Client', 'Operator' ),
	'demo_customer'   => array( 'customer', 'Demo', 'Customer' ),
);

$made = array();
foreach ( $accounts as $login => $spec ) {
	if ( empty( $passwords[ $login ] ) ) {
		WP_CLI::error( "no password supplied for {$login}" );
	}
	$existing = get_user_by( 'login', $login );
	$id       = wp_insert_user(
		array(
			'ID'         => $existing ? $existing->ID : 0,
			'user_login' => $login,
			'user_pass'  => $passwords[ $login ],
			'user_email' => str_replace( '_', '-', $login ) . '@example.invalid',
			'role'       => $spec[0],
			'first_name' => $spec[1],
			'last_name'  => $spec[2],
			'locale'     => 'en_US',
		)
	);
	if ( is_wp_error( $id ) ) {
		WP_CLI::error( $id->get_error_message() );
	}
	$made[ $login ] = $spec[0];
}

echo wp_json_encode( array( 'users' => $made ) ), "\n";
