<?php
/**
 * t16, AC-3: the English original owns the cost, in every supported update channel.
 *
 * t12 to t15 cover cost written on the original. This one covers the opposite attempt: a cost written straight
 * onto the Arabic translation. Before this feature it stuck, the two language versions disagreed, and an Arabic
 * order recorded a cost the original never had. wp-admin never allowed that, because WooCommerce Multilingual
 * replaces the value from the original on save_post; the programmatic channels do not go through save_post, so
 * the same rule is applied at WooCommerce's own write filters instead (see CostTranslationSync).
 *
 * For each channel and product type:
 *   1. an English product with an Arabic translation;
 *   2. the authoritative English cost, 100;
 *   3. an attempt to write 999 directly onto the Arabic product through that channel;
 *   4. what the cost ownership rule produced;
 *   5. an Arabic order, and the cost it recorded;
 *   6. everything else on the Arabic post: authored fields, the language and the translation group.
 *
 * The native CSV importer is a documented exception, and is asserted as one: it matches rows by SKU, a duplicate
 * shares the SKU of its original, so an import can only ever reach the original. It is not a way to set a
 * different Arabic cost; it changes the original and the change then flows outwards.
 *
 * @package MizzeySite\Tests\Integration
 */

namespace MizzeySite\Tests\Integration;

require_once __DIR__ . '/_bootstrap.php';
require_once __DIR__ . '/_workflows.php';

function t16_fmt( ?float $v ): string {
	return null === $v ? 'none' : rtrim( rtrim( number_format( $v, 2, '.', '' ), '0' ), '.' );
}

run(
	new Scenario( 't16-translation-cost-ownership', 'AC-3' ),
	function ( Scenario $s ): bool {
		$s->enable_cogs();
		$w      = new Workflows( $s );
		$ok_all = true;
		$n      = 0;

		Workflows::clear_sync_log();
		$s->on_finish( array( Workflows::class, 'clear_sync_log' ) );

		foreach ( array( 'crud-cli', 'rest-http', 'crud-web', 'admin-http', 'import-http' ) as $channel ) {
			foreach ( array( 'simple', 'variation' ) as $type ) {
				$tag = 'T16' . ( ++$n );
				if ( 'simple' === $type ) {
					$en = $w->simple( $tag, 100.0 );
					$w->translate( 'duplicate', $en );
					$ar = Workflows::ar_of( $en );
				} else {
					list( $pid, $vids ) = $w->variable( $tag, array( 'S' => 100.0, 'L' => 70.0 ) );
					$w->translate( 'duplicate', $pid );
					$en = $vids[0];
					$ar = Workflows::ar_of( $en );
				}
				if ( ! $ar ) {
					$s->note( "FAIL $channel $type: no Arabic counterpart" );
					$ok_all = false;
					continue;
				}

				$addressed_original = ( Workflows::sku_target( $ar ) === $en );
				$before        = Workflows::stored( $ar );
				$core_before   = Workflows::snapshot( $ar );
				$logged_before = count( Workflows::sync_log_lines() );

				$result = $w->set_cost( $channel, $ar, 999.0 );

				// Both snapshots are taken before the order below, which moves stock and sales counters itself.
				$ar_cost    = Workflows::cost( $ar );
				$en_cost    = Workflows::cost( $en );
				$after      = Workflows::stored( $ar );
				$core_after = Workflows::snapshot( $ar );
				$logged     = count( Workflows::sync_log_lines() ) > $logged_before;
				$order      = $w->order_cost( $ar, 'ar' );
				$moved      = Workflows::differences( $before, $after, 'variation' === $type );

				// What may not move: price, sale price, price index, stock and its configuration, SKU and status.
				// A variation's title is regenerated by WooCommerce on any save, which t14 measures in detail.
				$core_moved = array();
				foreach ( $core_before as $field => $value ) {
					if ( $core_after[ $field ] === $value || ( 'variation' === $type && 'post_title' === $field ) ) {
						continue;
					}
					$core_moved[] = sprintf( '%s %s -> %s', $field, var_export( $value, true ), var_export( $core_after[ $field ], true ) );
				}

				// wp-admin and the importer submit a whole product record, so anything else they write is their
				// own doing, not the cost rule. The code channels send a cost and nothing else, so for those the
				// whole stored post is held still.
				$whole_record = in_array( $channel, array( 'admin-http', 'import-http' ), true );
				$must_not_move = $whole_record ? $core_moved : $moved['authored'];

				// The importer addresses products by SKU, which a duplicate shares with its original, so a row
				// aimed at the translation reaches whichever of the two the lookup returns. Reaching the original
				// is a legitimate change that flows outwards; reaching the translation changes nothing, because
				// the original owns the cost. Both keep the two language versions in agreement.
				$importer  = 'import-http' === $channel;
				$want      = ( $importer && $addressed_original ) ? 999.0 : 100.0;
				$reachable = 'ok' === $result;

				if ( ! $reachable ) {
					// wp-admin cannot reach an Arabic variation at all: the Arabic parent of a translated variable
					// product carries no variations in this runtime, so its variations panel is empty. Recorded as
					// a fact about the catalogue, not as a pass: no cost can be written where no field exists.
					$ok = ( 100.0 === $ar_cost && 100.0 === $en_cost && ! $core_moved );
					$s->note( sprintf(
						'%s %s %s: the channel cannot reach the translation (%s). AR %s EN %s, unchanged',
						$ok ? 'OK  ' : 'FAIL',
						$channel,
						$type,
						$result,
						t16_fmt( $ar_cost ),
						t16_fmt( $en_cost )
					) );
					$ok_all = $ok_all && $ok;
					continue;
				}

				$consistent = ( $ar_cost === $want && $en_cost === $want
					&& ! is_nan( $order ) && abs( $order - $want ) < 0.001 );
				$ok = ( $consistent && ! $must_not_move && $before['lang'] === $after['lang'] && $before['trid'] === $after['trid'] );
				// Every channel that carried 999 into the data store and had it replaced must say so in the log.
				if ( ! $importer ) {
					$ok = $ok && $logged;
				}

				$s->note( sprintf(
					'%s %s %s: wrote 999 to the translation -> AR %s, EN %s (want %s for both), Arabic order recorded %s; language and translation group unchanged: %s; authored fields changed: %s; override logged: %s%s',
					$ok ? 'OK  ' : 'FAIL',
					$channel,
					$type,
					t16_fmt( $ar_cost ),
					t16_fmt( $en_cost ),
					t16_fmt( $want ),
					is_nan( $order ) ? 'nothing' : t16_fmt( $order ),
					( $before['lang'] === $after['lang'] && $before['trid'] === $after['trid'] ) ? 'yes' : 'NO',
					$must_not_move ? implode( '; ', $must_not_move ) : 'none',
					$logged ? 'yes' : 'no',
					$importer ? sprintf( ' | the importer matches by SKU, and the row reached the %s', $addressed_original ? 'English original, so the change flowed outwards' : 'translation, so nothing changed' ) : ''
				) );
				if ( $whole_record && $moved['authored'] ) {
					$s->note( '     also written by the channel itself, not by the cost rule: ' . implode( '; ', $moved['authored'] ) );
				}
				$ok_all = $ok_all && $ok;
			}
		}

		$s->note( 'Unsupported by design, and not detectable: a direct database or update_post_meta() write bypasses the WooCommerce data store, so no filter can see it. The project forbids direct meta writes on products (woo-guard rule 2).' );
		$s->note( 'Not bidirectional: nothing here lets a translation become the source of a cost. The original is the only copy that can change it.' );
		return $ok_all;
	}
);
