"""Generate one dossier per epic from the datasets.

    python -m discovery.gen_epic_dossiers

Output goes to generated/. Never hand-edit it: the next run overwrites.
"""

import io
import os
import sys

from discovery import riskset, schema

OUT = os.path.join(os.path.dirname(os.path.abspath(__file__)), 'generated')


def _cell(value):
    """A markdown table cell. A pipe in the content would split the row."""
    return str(value).replace('|', r'\|')


def dossier(epic, stories, verdicts, probes, plugins):
    """The markdown for one epic."""
    rows = [s for s in stories if s['epic'] == epic]
    if not rows:
        return ''
    by_story = {v['story']: v for v in verdicts}
    probe_by_id = {p['id']: p for p in probes}
    risky = riskset.risk_set(stories)

    o = io.StringIO()
    w = o.write
    w('# %s: %s\n\n' % (epic, rows[0]['epicname']))
    w('Generated. Do not edit this file. Correct the dataset and regenerate.\n\n')
    w('%d stories, %d points. Claimed leverage: %s.\n\n'
      % (len(rows), sum(s['points'] for s in rows), rows[0]['leverage']))

    validated = sum(1 for s in rows if s['id'] in by_story)
    w('Validated: %d of %d.\n\n' % (validated, len(rows)))

    w('## Stories\n\n')
    w('| Story | Title | Trace | Set | Claimed | Actual | Confidence | Points |\n')
    w('|---|---|---|---|---|---|---|---|\n')
    for s in rows:
        v = by_story.get(s['id'])
        in_set = 'risk' if s['id'] in risky else 'light'
        if v:
            actual, confidence = v.get('actual') or '', v.get('confidence') or ''
            flag = v.get('points_flag') or 'ok'
            points = '%d (%s)' % (s['points'], flag) if flag != 'ok' else str(s['points'])
        else:
            actual, confidence, points = 'not yet validated', '', str(s['points'])
        w('| %s | %s | %s | %s | %s | %s | %s | %s |\n'
          % (s['id'], _cell(s['title']), _cell(s['trace']), in_set,
             s['leverage'], actual, confidence, points))
    w('\n')

    risks = [(s, by_story[s['id']]) for s in rows
             if s['id'] in by_story and (by_story[s['id']].get('risk') or '').strip()]
    if risks:
        w('## Risks\n\n')
        for s, v in risks:
            w('**%s, %s.** %s\n\n' % (s['id'], s['title'], v['risk']))

    evidence = sorted({pid for s in rows if s['id'] in by_story
                       for pid in (by_story[s['id']].get('evidence') or [])})
    if evidence:
        w('## Evidence\n\n')
        w('| Probe | Question | Verdict |\n|---|---|---|\n')
        for pid in evidence:
            p = probe_by_id.get(pid, {})
            w('| %s | %s | %s |\n' % (pid, _cell(p.get('question', 'unknown probe')),
                                      p.get('verdict') or 'not yet run'))
        w('\n')

    questions = [(s['id'], q) for s in rows if s['id'] in by_story
                 for q in (by_story[s['id']].get('open') or [])]
    if questions:
        w('## Open questions\n\n')
        for sid, q in questions:
            w('- **%s.** %s\n' % (sid, q))
        w('\n')

    return o.getvalue()


def main():
    stories = schema.load_stories()
    verdicts = schema.load('verdicts')
    probes = schema.load('probes')
    plugins = schema.load('plugins')
    os.makedirs(OUT, exist_ok=True)
    epics = sorted({s['epic'] for s in stories})
    for epic in epics:
        text = dossier(epic, stories, verdicts, probes, plugins)
        path = os.path.join(OUT, 'epic-%s.md' % epic)
        with open(path, 'w', encoding='utf-8') as fh:
            fh.write(text)
    print('%d dossiers written to generated/' % len(epics))
    return 0


if __name__ == '__main__':
    sys.exit(main())
