"""The consolidated validation report.

    python -m discovery.gen_validation_report

Refuted probes lead, because a refuted probe means the Technical Design says
something untrue and something downstream has to change.
"""

import io
import os
import sys

from discovery import riskset, schema

OUT = os.path.join(os.path.dirname(os.path.abspath(__file__)), 'generated')


def report(data):
    risky = riskset.risk_set(data.stories)
    by_story = {v['story']: v for v in data.verdicts}
    o = io.StringIO()
    w = o.write

    w('# Validation Report\n\n')
    w('Generated. Do not edit this file. Correct the dataset and regenerate.\n\n')
    validated = sum(1 for sid in risky if sid in by_story)
    w('Risk-weighted set validated: %d of %d.\n' % (validated, len(risky)))
    w('Probes run: %d of %d.\n\n'
      % (sum(1 for p in data.probes if p.get('verdict')), len(data.probes)))

    refuted = [p for p in data.probes if p.get('verdict') == 'refuted']
    w('## Refuted\n\n')
    if refuted:
        w('The Technical Design asserts something these probes did not find. '
          'Each one needs a disposition under the design, section 8.\n\n')
        for p in refuted:
            w('### %s\n\n' % p['id'])
            w('**Question.** %s\n\n' % p['question'])
            w('**The design assumed.** %s\n\n' % p['expected'])
            w('**Observed.** %s\n\n' % p['observed'])
            if p.get('gap_rows'):
                w('**Technical Design rows affected.** %s\n\n'
                  % ', '.join(str(r) for r in p['gap_rows']))
    else:
        w('Nothing refuted.\n\n')

    partial = [p for p in data.probes if p.get('verdict') == 'partial']
    w('## Partial\n\n')
    if partial:
        for p in partial:
            w('- **%s.** %s Observed: %s\n' % (p['id'], p['question'], p['observed']))
        w('\n')
    else:
        w('Nothing partial.\n\n')

    confirmed = [p for p in data.probes if p.get('verdict') == 'confirmed']
    w('## Confirmed\n\n')
    if confirmed:
        for p in confirmed:
            w('- **%s.** %s\n' % (p['id'], p['question']))
        w('\n')
    else:
        w('Nothing confirmed yet.\n\n')

    drift = [(sid, by_story[sid]) for sid in sorted(risky)
             if sid in by_story and by_story[sid].get('points_flag') != 'ok']
    w('## Estimate drift\n\n')
    if drift:
        w('Stage 4 already runs at 68 points a week and Stage 5 at 92, against a 55 '
          'average. These flags compound that.\n\n')
        w('| Story | Flag | Risk |\n|---|---|---|\n')
        for sid, v in drift:
            w('| %s | %s | %s |\n' % (sid, v['points_flag'], v.get('risk', '')))
        w('\n')
    else:
        w('No story is flagged under or over.\n\n')

    questions = [(v['story'], q) for v in data.verdicts for q in (v.get('open') or [])]
    w('## Open questions\n\n')
    if questions:
        for sid, q in questions:
            w('- **%s.** %s\n' % (sid, q))
        w('\n')
    else:
        w('None outstanding.\n\n')

    return o.getvalue()


def main():
    text = report(schema.load_data())
    os.makedirs(OUT, exist_ok=True)
    with open(os.path.join(OUT, 'validation-report.md'), 'w', encoding='utf-8') as fh:
        fh.write(text)
    print('validation-report.md written')
    return 0


if __name__ == '__main__':
    sys.exit(main())
