"""The plugin register, with the total measured against what the client was quoted.

    python -m discovery.gen_plugin_register
"""

import io
import os
import sys

from discovery import schema

OUT = os.path.join(os.path.dirname(os.path.abspath(__file__)), 'generated')


def register(plugins):
    o = io.StringIO()
    w = o.write
    w('# Plugin Register\n\n')
    w('Generated. Do not edit this file. Correct the dataset and regenerate.\n\n')

    decided = [p for p in plugins if p.get('decision')]
    outstanding = [p for p in plugins if not p.get('decision')]

    w('## Decided\n\n')
    if decided:
        w('| Id | Need | Decision | Licence | Annual cost | Licence held by |\n')
        w('|---|---|---|---|---|---|\n')
        for p in decided:
            cost = ('%s %s' % (p.get('cost_annual'), p.get('currency', 'USD'))
                    if p.get('cost_annual') else 'nil')
            w('| %s | %s | %s | %s | %s | %s |\n'
              % (p['id'], p['need'], p['decision'], p.get('licence') or 'none',
                 cost, p.get('owner') or ''))
        w('\n')
    else:
        w('Nothing decided yet.\n\n')

    total = sum(p.get('cost_annual') or 0 for p in decided
                if (p.get('currency') or 'USD') == 'USD')
    w('**Total, USD a year: %d.** Quoted to the client in Technical Design section 11: '
      'about %d.\n\n' % (total, schema.QUOTED_ANNUAL_USD))
    if total > schema.QUOTED_ANNUAL_USD:
        w('> This exceeds the figure already in the client\'s hands. It is a commercial '
          'conversation, not a technical one.\n\n')

    w('## Outstanding\n\n')
    if outstanding:
        for p in outstanding:
            w('- **%s.** %s, not yet decided.\n' % (p['id'], p['need']))
        w('\n')
    else:
        w('Every need is decided.\n\n')

    return o.getvalue()


def main():
    text = register(schema.load('plugins'))
    os.makedirs(OUT, exist_ok=True)
    with open(os.path.join(OUT, 'plugin-register.md'), 'w', encoding='utf-8') as fh:
        fh.write(text)
    print('plugin-register.md written')
    return 0


if __name__ == '__main__':
    sys.exit(main())
