"""One document per journey.

    python -m discovery.gen_journey_docs
"""

import io
import os
import sys

from discovery import schema

OUT = os.path.join(os.path.dirname(os.path.abspath(__file__)), 'generated')


def journey_doc(journey, stories):
    titles = {s['id']: s['title'] for s in stories}
    o = io.StringIO()
    w = o.write
    w('# %s: %s\n\n' % (journey['id'], journey['name']))
    w('Generated. Do not edit this file. Correct the dataset and regenerate.\n\n')
    w('Actor: %s. Language: %s.\n\n' % (journey['actor'], journey['language']))

    w('## Steps\n\n')
    w('| Step | What happens | Stories | Screen |\n|---|---|---|---|\n')
    for step in journey.get('steps', []):
        named = ', '.join('%s (%s)' % (sid, titles.get(sid, 'unknown'))
                          for sid in step.get('stories', []))
        w('| %s | %s | %s | %s |\n'
          % (step.get('n'), step.get('description', ''), named, step.get('screen', '')))
    w('\n')

    gaps = journey.get('gaps') or []
    w('## Gaps this journey exposes\n\n')
    if gaps:
        w('Failures visible only across stories, which no single story shows.\n\n')
        for g in gaps:
            w('- %s\n' % g)
        w('\n')
    else:
        w('None recorded.\n\n')

    return o.getvalue()


def main():
    stories = schema.load_stories()
    journeys = schema.load('journeys')
    os.makedirs(OUT, exist_ok=True)
    for j in journeys:
        path = os.path.join(OUT, 'journey-%s.md' % j['id'])
        with open(path, 'w', encoding='utf-8') as fh:
            fh.write(journey_doc(j, stories))
    print('%d journey document(s) written' % len(journeys))
    return 0


if __name__ == '__main__':
    sys.exit(main())
